var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                      o                                         ",
   "                                           xxx                                  ",
   "                                            o                                   ",
   "                                               E                                ",   
   "                                                  xxx                           ",
   "                                                   o                            ",
   "                                                     N                          ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                    R                                           ",
   "                                  xxxxx                                         ",
   "                                                                                ",
   "                            o                                               xxxx",
   "xxxx                      xxxxx                                              x  ",
   "  x              o                                                           x  ",
   "  x            xxxxx                                                    E  o x  ",
   "  x                                                                          x  ",
   "  x  @                                    o          G                       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!!!!xxx!!!!!!!xxxxxx  ",
   "                        x!!!!!!!!!!!!!!!x            x!!!!!!!!!x!!!!!!!!x       ",
   "                        x!!!!!!!!!!!!!!!x            x!!!!!!!!!x!!!!!!!!x       ",
   "                        x!!!!!!!!!!!!!!!x            x!!!!!!!!!x!!!!!!!!x       ",
   "                        xxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxx       ",
   "                                                                                ",
   "                                                                                "],
   
  ["!!!!!v!!!!x!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "          x!!!!v!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "          xxxxx                   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oo   N   ",
   "  @       x                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ",
   "xxxx      x                        vvvvvvvvv vvvvvvvvv vvvvvvvvvv vvvvvvvv vvvvvvvv vvvvvvvvv                 ",
   "          x       xxxx  xxx                                                                                   ",
   "          x         o                                                                                         ",
   "         ox                                                                                                   ",
   "        xxx            o N      SI                                                           R                ",
   "o         x          xxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             o  ",
   "xxx       x          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            xxxxx",
   "          x          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                 ",
   "         ox          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o     E        ",
   "        xxx          x          xxxxx   xxxxxxxxxxx           xxxxxxxxxxx   xxxxxx          xxxxxx            ",
   "          x          x                  x!!!!!!!!!x           x!!!!!!!!!x                   x                 ",
   "          x          x                  x!!!!!!!!!x           x!!!!!!!!!x                   x                 ",
   "o         x       xxxx                  xxxxxvxxxxx           xxxxxvxxxxx                   x                 ",
   "xxx       x          x                  o         o           o         o                   x  o              ",
   "          x          x                                                                      xxxxxx            ",
   "         ox          x                                                       xxxxxx                          x",
   "     E  xxx          x                                                                                      x!",
   "          x          x                                                                           xxx      ox!!",
   "o         x          x                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 x!!!",
   "xxx       x          x                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                x!!!!",
   "          x          x                  x!!!xxxxxxvxxxxxxxxxxxvxxxxxx!!!x                               x!!!!!",
   "       xxxxxxxx      x                  x!!!x   o        o         ox!!!x                              x!!!!!!",
   "                     x                xxxxxxx                       xxxxxxx                          ox!!!!!!!",
   "o                    x                                                                               x!!!!!!!!",
   "xxx                  x                                                                              x!!!!!!!!!",
   "    o    o    R      x                                                                            = !!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"] ,
   
  [
   "                                                                                                              ",  
   "                                                                                                              ",  
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "            o   o                                        oo                                                   ",
   "                                                  xx    xxxx                                                  ",
   "           ooooooo                                                                                            ",
   "         xxxxxxxxxxxxx                                                                                        ",
   "                            o G             o G                                                               ",
   "                       x    xxxxxx  xx    xxxxx    o                                                          ",
   "                                          xxxxx   xxx     G o                                                =",
   "                xxx                       xx!xx          xxxxx              xx      xx                        ",
   "          xxx   x!x                         v            x!!!x                                                ",
   "          x!x    v                                         v   xx       o                                 =   ",
   "           v       xxx                                                 xxx                  xx                ",
   "                   x!x                                                 x!x                                    ",
   "       xxx          v                                                   v                                     ",
   "       x!x                                                                               xx                   ",
   "        v                                                                                                     ",
   "                                                                                  o   G                       ",
   "                                                                             xx   xxxxx                       ",
   "                                                                        o          x!x                        ",
   "                                                           E          xxxxx         v  xx                 xxxx",
   "                                                    o            o     x!x                                =!!!",
   "                                                 xxxxxxx       xxxxx    v                                  x!!",
   "                                                  x!!!x         x!x                       xxxx              x!",
   "                                          o        xvx           v                                          =!",
   "                                        xxxx                                                             xx!!!",
   "                                o                   o            o      o           o                  =!!!!!!",
   "                         o     xxxx                                                           xxxxxxxxxxxxxxxx",
   "               o        xxxx                                                                                  ",
   "            xxxx                                                        E           E                         ",
   "    @                                                                         o                    oooooo     ",
   "xxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "        x!!!!!!!!!!!!x                                                                                        ",
   "        x!!!!!!!!!!!!x                                                                                        ",
   "        xxxxxxxxxxxxxx                                                                                        "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "          o          o                                    S                o           o                          ",
   "                                                                                                                  ",
   "                                                                                                           xxxxxx ",
   "                               x                              o                o                             o    ",
   "                               x                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       ",
   "                               x                        D!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     xxxxxx            ",
   "                               x                       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       o               ",
   "                               x                    D!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      =",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  D!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                xxxxxx ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!vxx                 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                  o    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!v   x              D!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!v     x            D!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     xxxxxx            ",
   "!!!!!!!!!!!!!!!!!!!!!!!v       x          D!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       o               ",
   "!!!!!!!!!!!!!!!!!!!!!v         x        D!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      =",
   "!!!!!!!!!!!!!!!!!!!v           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                xxxxxx ",
   "!!!!!!!!!!!!!!!!!v             xxxxxvxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  o    ",
   "!!!!!!!!!!!!!!!v               x                o            o              o                                    =",
   "!!!!!!!!!!!!!v                 x                                                                xxxxxx            ",
   "!!!!!!!!!!!v                                                                               x      o               ",
   "!!!!!!!!!v                                                                                 x                      ",
   "!!!!!!!!v                                                                                  x                      ",
   "!!!!!!!v                                o                                                  x                      ",
   "xxxxxxx                           o    xxx             o     E     o   E     o   E   R     x      o               ",
   "                                  x                   xxxxx      xxxx     xxxxxx   xxxx    x!!!!xxxxxx!!!!!!!!!!!!",
   "                                  x                                                        x!!!!!!!!!!!!!!!!!!!!!!",
   "x                                xx               o                                       Dx!!!!!!!!!!!!!!!!!!!!!!",
   "x                               xxx!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!",
   "x@    S        o        o      xxxx!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
